version: '1.0'

services:
  api:
    container_name: nest-api-postgres
    depends_on:
      - redis
      - postgres
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # env_file:
    #   - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST:=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      # - REDIS_USERNAME:default
      # - REDIS_PASSWORD:fbX4PgCelRue3exBCWFETglpCkrzehiB

    ports:
      - 3000:3000
    command: yarn run start:dev
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  k6:
    image: loadimpact/k6:latest
    #    entrypoint: /bin/sh
    #    user: root
    # networks:
    #   - k6
    ports:
      - '6565:6565'
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
  influxdb:
    image: influxdb:1.8
    #    entrypoint: /bin/sh
    #    user: root
    # networks:
    #   - k6
    #   - grafana
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    #    entrypoint: /bin/sh
    #    user: root
    # networks:
    #   - grafana
    ports:
      - '4000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

volumes:
  postgres:
  redis:
    driver: local
